version: '2'
services:
  tomcat:
    image: tomcat
    volumes:
      - ./build/libs/demo-0.0.1-SNAPSHOT-plain.war:/usr/local/tomcat/webapps/demo-0.0.1-SNAPSHOT-plain.war
    ports:
      - "8080:8080"